export const BREAKING_KEYWORDS = [
  "breaking",
  "viral",
  "trending",
  "controversy",
  "controversial",
  "backlash",
  "outrage",
  "exposed",
  "leaked",
  "roast",
  "beef",
  "fight",
  "drama",
  "statement",
  "reacts",
  "response",
  "responds",
  "accused",
  "claims",
  "debate",
  "shocking",
  "panic",
  "warning",
  "threat",
  "boycott",
  "cancelled",
  "apology",
  "criticized",
  "slammed",
  "praised",
  "internet reacts",
  "fans react",
  "massive reaction",
  "social media storm",
  "breaking news",
  "big update",
  "latest update",
  "headline",
  "spotlight",
  "livestream",
  "podcast clip",
  "interview",
  "announcement",
  "revealed",
  "deleted post",
  "tweet",
  "instagram story",
  "youtube shorts",
  "stream",
  "online trend",
  "internet sensation",
  "buzz",
  "hot topic",
  "going viral",
];

export const HAPPENING_KEYWORDS = [
  "happening",
  "trending",
  "in news",
  "viral",
  "making headlines",
  "sparks debate",
  "gains attention",
  "reacting",
  "responds",
  "shares",
  "posted",
  "announced",
  "criticized",
  "praised",
  "slammed",
  "accused",
  "involved",
  "discussed",
  "surfaced",
  "revealed",
  "claims",
  "says",
  "reports",
  "launches",
  "collaborates",
  "appears",
  "supports",
  "opposes",
  "comments",
  "opens up",
  "addresses",
  "confirms",
  "denies",
  "apologizes",
  "celebrates",
  "attends",
  "streams",
  "uploads",
  "trends",
  "featured",
];

export const NEWS_KEYWORDS = [
  "snake venom",
  "snake venom case",
  "wildlife act",
  "wildlife protection act",
  "ndps",
  "supreme court",
  "high profile case",
  "criminal proceedings",
  "legal battle",
  "justice prevailed",
  "court verdict",
  "court order",
  "quashed fir",
  "fresh proceedings",

  // Controversies
  "orry",
  "orry row",
  "influencer drama",
  "social media buzz",
  "viral news",
  "breaking news",
  "online controversy",
  "viral controversy",
  "speculation",
  "public response",
  "internet reacts",

  // Creator news
  "bigg boss",
  "bigg boss ott",
  "winner",
  "show appearance",
  "guest appearance",
  "media coverage",
  "press conference",
  "news update",

  // Politics / public discussions
  "political statement",
  "government",
  "minister",
  "election",
  "public issue",
  "national issue",
  // Legal & Court
  "court",
  "high court",
  "supreme court",
  "legal",
  "lawsuit",
  "case",
  "court case",
  "court hearing",
  "petition",
  "notice",
  "summons",
  "fir",
  "police complaint",
  "investigation",
  "under investigation",
  "crime branch",
  "cyber cell",
  "arrest",
  "detained",
  "custody",
  "bail",
  "chargesheet",
  "legal action",
  "defamation",
  "hearing",
  "judge",
  "warrant",

  // Controversy
  "controversy",
  "controversial",
  "backlash",
  "boycott",
  "cancelled",
  "cancel culture",
  "criticism",
  "criticized",
  "criticised",
  "slammed",
  "called out",
  "exposed",
  "allegation",
  "allegedly",
  "accused",
  "response",
  "clarification",
  "statement",
  "public reaction",
  "social media outrage",
  "apology",
  "issue",
  "dispute",
  "conflict",
  "drama",

  // News / Media
  "breaking",
  "exclusive",
  "report",
  "reported",
  "reports",
  "revealed",
  "confirmed",
  "official",
  "officially",
  "announcement",
  "announced",
  "update",
  "latest",
  "news",
  "development",
  "media reports",
  "sources claim",
  "claims",
  "reaction",
  "addressed",

  // Business / Career
  "brand deal",
  "partnership",
  "investment",
  "startup",
  "business",
  "company",
  "acquisition",
  "funding",
  "contract",
  "endorsement",
  "net worth",
  "earnings",

  // Shows / Professional
  "show announcement",
  "season",
  "new show",
  "guest appearance",
  "interview",
  "podcast appearance",
  "award",
  "nomination",
  "winner",
  "netflix",
  "amazon prime",
  "hotstar",
  "television",
  "tv show",

  // Sensitive
  "death",
  "hospital",
  "injury",
  "accident",
  "health update",
  "security issue",
  "threat",
  "attack",
  "fraud",
  "scam",
  "hack",
  "leaked",
  "leak",
  "global",
  "record",
  "failed",
  "socially",
  "emotional",
  "spoke",
  "against",
  "interview",
  "cryptic",
  "note",
  "powerfull",
  "unpredictable",
  "serious",
  "circuit",
  "still alive",
  "opened up",
  "internet",
  "sunil pal",
  "laughter chefs",
];

export const FUN_KEYWORDS = [
  "vlog",
  "daily life",
  "day in my life",
  "travel",
  "vacation",
  "trip",
  "airport",
  "family",
  "friends",
  "birthday",
  "celebration",
  "weekend",
  "outing",

  // Comedy
  "funny",
  "comedy",
  "joke",
  "jokes",
  "meme",
  "memes",
  "roast",
  "banter",
  "laugh",
  "hilarious",
  "viral moment",
  "reaction video",

  // Edits / Fan Content
  "edit",
  "fan edit",
  "tribute",
  "fanpage",
  "fan moment",
  "montage",
  "compilation",
  "best moments",
  "throwback",

  // Music
  "song",
  "music",
  "album",
  "track",
  "single",
  "music video",
  "lyrical",
  "dance",
  "performance",
  "dj",
  "remix",

  // Reels / Shorts
  "reel",
  "reels",
  "shorts",
  "instagram reel",
  "youtube shorts",
  "challenge",
  "trend",
  "trending",
  "viral",
  "dance trend",

  // Gaming
  "gaming",
  "gameplay",
  "stream",
  "livestream",
  "stream clip",
  "esports",
  "chess",
  "valorant",
  "bgmi",
  "minecraft",

  // Creator Moments
  "wholesome",
  "cute",
  "heartwarming",
  "emotional",
  "friendship",
  "creator moment",
  "podcast clip",
  "fun clip",
  "behind the scenes",
  "bts",

  // Entertainment
  "collab",
  "collaboration",
  "prank",
  "challenge video",
  "fun challenge",
  "trailer",
  "teaser",
  "episode",
  "show clip",
  "movie release",
  "web series",
  "entertainment",

  // Lifestyle
  "fitness",
  "food",
  "cooking",
  "shopping",
  "fashion",
  "style",
  "makeover",
  "routine",
  "life update",

  // Social Media
  "instagram",
  "youtube video",
  "creator post",
  "viral reel",
  "viral clip",
  "fan interaction",
  "qna",
  "ask me anything",
  // Elvish branding
  "rao sahab",
  "elvish army",
  "system",
  "system hang",
  "elvishians",

  // Lifestyle
  "luxury car",
  "supercar",
  "car collection",
  "new car",
  "bike ride",
  "road trip",
  "farmhouse",
  "village life",
  "haryana",
  "gurgaon",

  // Friends & gang
  "gang",
  "boys",
  "brothers",
  "friendship",
  "club",
  "club scene",
  "party",
  "nightlife",
  "ladai",
  "fight clip",
  "funny fight",

  // Music
  "chand mera dil",
  "romantic",
  "love song",
  "music reel",
  "sad song",
  "heartbreak",
  "shayari",
  "poetry",

  // Spiritual
  "mahadev",
  "shiv",
  "har har mahadev",
  "faith",
  "spiritual",
  "blessings",
  "god",
  "temple",
  "pendant",
  "positive energy",

  // Fan content
  "fan edit",
  "elvish edit",
  "viral edit",
  "army edit",
  "tribute edit",

  // Daily creator content
  "behind the scenes",
  "bts",
  "vlog",
  "travel vlog",
  "daily vlog",
  "creator life",
  "fun conversation",
  "live stream",
  "podcast clip",

  // Brand promotions
  "link in bio",
  "download now",
  "promo",
  "promotion",
  "brand collaboration",
  "partnered with",
  "sponsored",

  // Social content
  "reels",
  "fyp",
  "explore",
  "trending reel",
  "viral reel",
  "challenge",
  "funny moment",
];

export const CREATOR_NAMES = [
  {
    name: "Samay_Raina",
    keywords: [
      "samay raina",
      "india's got latent",
      "indias got latent",
      "samay raina controversy",
      "samay raina news",
      "samay raina FIR",
      "samay raina court case",
      "samay raina legal notice",
      "indias got latent",
      "samay raina apology",
      "samay raina comeback",
    ],
    channelName: "@SamayRainaOfficial",
  },
  {
    name: "Elvish_Yadav",
    keywords: [
      "rao sahab",
      "elvishyadav",
      "elvisharmy",
      "elvish",
      "systemclothing",
      "elvishians",
      "elvishsquad",
      "rao_sahab",
      "elvishyadavvlogs",
      "elvishyadavfans",
      "elvishyadavofficial",
      "elvisharmyofficial",
      "systumm",
      "elvishbhaiii",
      "raosahab",
    ],
    channelName: "@ElvishYadavVlogs",
  },
  {
    name: "Urfi_Javed",
    keywords: [
      "urfi javed",
      "urfi javed latest",
      "urfi javed news",
      "urfi javed controversy",
      "urfi javed viral",
      "urfi javed trending",
      "urfi javed interview",
      "urfi javed reaction",
      "urfi javed statement",
      "urfi javed fashion",
      "urfi javed outfit",
      "urfi javed dress",
      "urfi javed style",
      "urfi javed instagram",
      "urfi javed youtube",
      "urfi javed twitter",
      "urfi javed reality show",
      "urfi javed latest update",
      "urfi javed viral video",
      "urfi javed breaking news",
    ],
    channelName: "@urfijaved",
  },
  {
    name: "Ranveer_Allahbadia",
    keywords: [
      "ranveer allahbadia",
      "beerbiceps",
      "beer biceps",
      "ranveer allahbadia latest",
      "ranveer allahbadia news",
      "ranveer allahbadia controversy",
      "ranveer allahbadia viral",
      "ranveer allahbadia trending",
      "ranveer allahbadia interview",
      "ranveer allahbadia podcast",
      "ranveer allahbadia reaction",
      "ranveer allahbadia statement",
      "ranveer allahbadia youtube",
      "ranveer allahbadia instagram",
      "beerbiceps podcast",
      "the ranveer show",
      "trs podcast",
      "ranveer allahbadia latest update",
      "ranveer allahbadia breaking news",
      "ranveer allahbadia viral clip",
    ],
    channelName: "@BeerBiceps",
  },
  {
    name: "Munawar_Faruqui",
    keywords: [
      "munawar faruqui",
      "munawar faruqui latest",
      "munawar faruqui news",
      "munawar faruqui controversy",
      "munawar faruqui viral",
      "munawar faruqui trending",
      "munawar faruqui interview",
      "munawar faruqui reaction",
      "munawar faruqui statement",
      "munawar faruqui standup",
      "munawar faruqui comedy",
      "munawar faruqui live",
      "munawar faruqui instagram",
      "munawar faruqui youtube",
      "munawar faruqui twitter",
      "munawar faruqui bigg boss",
      "munawar faruqui winner",
      "munawar faruqui latest update",
      "munawar faruqui breaking news",
      "munawar faruqui viral video",
    ],
    channelName: "@MunawarFaruqui",
  },
  {
    name: "Dhruv_Rathee",
    keywords: [
      "dhruv rathee",
      "dhruv rathee latest",
      "dhruv rathee news",
      "dhruv rathee controversy",
      "dhruv rathee viral",
      "dhruv rathee trending",
      "dhruv rathee interview",
      "dhruv rathee reaction",
      "dhruv rathee statement",
      "dhruv rathee youtube",
      "dhruv rathee instagram",
      "dhruv rathee twitter",
      "dhruv rathee politics",
      "dhruv rathee analysis",
      "dhruv rathee fact check",
      "dhruv rathee latest video",
      "dhruv rathee latest update",
      "dhruv rathee breaking news",
      "dhruv rathee viral clip",
      "dhruv rathee explained",
    ],
    channelName: "@DhruvRathee",
  },
  {
    name: "Ajey_Nagar",
    keywords: [
      "ajey nagar",
      "carryminati",
      "carry minati",
      "carryminati latest",
      "carryminati news",
      "carryminati controversy",
      "carryminati viral",
      "carryminati trending",
      "carryminati roast",
      "carryminati reaction",
      "carryminati statement",
      "carryminati youtube",
      "carryminati instagram",
      "carryminati gaming",
      "carryislive",
      "carry is live",
      "ajey nagar latest update",
      "carryminati latest update",
      "carryminati breaking news",
      "carryminati viral video",
    ],
    channelName: "@CarryMinati",
  },
  {
    name: "Bhuvan_Bam",
    keywords: [
      "bhuvan bam",
      "bb ki vines",
      "bbkivines",
      "bhuvan bam latest",
      "bhuvan bam news",
      "bhuvan bam viral",
      "bhuvan bam trending",
      "bhuvan bam interview",
      "bhuvan bam reaction",
      "bhuvan bam statement",
      "bhuvan bam youtube",
      "bhuvan bam instagram",
      "bb ki vines latest",
      "bhuvan bam web series",
      "bhuvan bam taaza khabar",
      "bhuvan bam comedy",
      "bhuvan bam latest update",
      "bhuvan bam breaking news",
      "bhuvan bam viral clip",
      "bb ki vines news",
    ],
    channelName: "@BBKiVines",
  },
  {
    name: "Abhishek_Malhan",
    keywords: [
      "abhishek malhan",
      "fukra insaan",
      "fukra insan",
      "abhishek malhan latest",
      "abhishek malhan news",
      "abhishek malhan controversy",
      "abhishek malhan viral",
      "abhishek malhan trending",
      "abhishek malhan interview",
      "abhishek malhan reaction",
      "abhishek malhan statement",
      "fukra insaan latest",
      "fukra insaan youtube",
      "abhishek malhan instagram",
      "fukra insaan vlog",
      "bigg boss ott abhishek malhan",
      "abhishek malhan latest update",
      "abhishek malhan breaking news",
      "abhishek malhan viral video",
      "fukra insaan news",
    ],
    channelName: "@FukraInsaan",
  },
  {
    name: "Apoorva_Mukhija",
    keywords: [
      "apoorva mukhija",
      "the rebel kid",
      "rebel kid",
      "apoorva mukhija latest",
      "apoorva mukhija news",
      "apoorva mukhija controversy",
      "apoorva mukhija viral",
      "apoorva mukhija trending",
      "apoorva mukhija interview",
      "apoorva mukhija reaction",
      "apoorva mukhija statement",
      "apoorva mukhija instagram",
      "apoorva mukhija youtube",
      "the rebel kid latest",
      "the rebel kid controversy",
      "india's got latent apoorva",
      "apoorva mukhija latest update",
      "apoorva mukhija breaking news",
      "apoorva mukhija viral clip",
      "rebel kid news",
    ],
    channelName: "@TheRebelKid",
  },
];
