export const BREAKING_KEYWORDS = [
  "breaking",
  "viral",
  "trending",
  "controversy",
  "controversial",
  "backlash",
  "outrage",
  "exposed",
  "leaked",
  "roast",
  "beef",
  "fight",
  "drama",
  "statement",
  "reacts",
  "response",
  "responds",
  "accused",
  "claims",
  "debate",
  "shocking",
  "panic",
  "warning",
  "threat",
  "boycott",
  "cancelled",
  "apology",
  "criticized",
  "slammed",
  "praised",
  "internet reacts",
  "fans react",
  "massive reaction",
  "social media storm",
  "breaking news",
  "big update",
  "latest update",
  "headline",
  "spotlight",
  "livestream",
  "podcast clip",
  "interview",
  "announcement",
  "revealed",
  "deleted post",
  "tweet",
  "instagram story",
  "youtube shorts",
  "stream",
  "online trend",
  "internet sensation",
  "buzz",
  "hot topic",
  "going viral",
];

export const HAPPENING_KEYWORDS = [
  "happening",
  "trending",
  "in news",
  "viral",
  "making headlines",
  "sparks debate",
  "gains attention",
  "reacting",
  "responds",
  "shares",
  "posted",
  "announced",
  "criticized",
  "praised",
  "slammed",
  "accused",
  "involved",
  "discussed",
  "surfaced",
  "revealed",
  "claims",
  "says",
  "reports",
  "launches",
  "collaborates",
  "appears",
  "supports",
  "opposes",
  "comments",
  "opens up",
  "addresses",
  "confirms",
  "denies",
  "apologizes",
  "celebrates",
  "attends",
  "streams",
  "uploads",
  "trends",
  "featured",
];

export const NEWS_KEYWORDS = [
  "snake venom",
  "snake venom case",
  "wildlife act",
  "wildlife protection act",
  "ndps",
  "supreme court",
  "high profile case",
  "criminal proceedings",
  "legal battle",
  "justice prevailed",
  "court verdict",
  "court order",
  "quashed fir",
  "fresh proceedings",

  // Controversies
  "orry",
  "orry row",
  "influencer drama",
  "social media buzz",
  "viral news",
  "breaking news",
  "online controversy",
  "viral controversy",
  "speculation",
  "public response",
  "internet reacts",

  // Creator news
  "bigg boss",
  "bigg boss ott",
  "winner",
  "show appearance",
  "guest appearance",
  "media coverage",
  "press conference",
  "news update",

  // Politics / public discussions
  "political statement",
  "government",
  "minister",
  "election",
  "public issue",
  "national issue",
  // Legal & Court
  "court",
  "high court",
  "supreme court",
  "legal",
  "lawsuit",
  "case",
  "court case",
  "court hearing",
  "petition",
  "notice",
  "summons",
  "fir",
  "police complaint",
  "investigation",
  "under investigation",
  "crime branch",
  "cyber cell",
  "arrest",
  "detained",
  "custody",
  "bail",
  "chargesheet",
  "legal action",
  "defamation",
  "hearing",
  "judge",
  "warrant",

  // Controversy
  "controversy",
  "controversial",
  "backlash",
  "boycott",
  "cancelled",
  "cancel culture",
  "criticism",
  "criticized",
  "criticised",
  "slammed",
  "called out",
  "exposed",
  "allegation",
  "allegedly",
  "accused",
  "response",
  "clarification",
  "statement",
  "public reaction",
  "social media outrage",
  "apology",
  "issue",
  "dispute",
  "conflict",
  "drama",

  // News / Media
  "breaking",
  "exclusive",
  "report",
  "reported",
  "reports",
  "revealed",
  "confirmed",
  "official",
  "officially",
  "announcement",
  "announced",
  "update",
  "latest",
  "news",
  "development",
  "media reports",
  "sources claim",
  "claims",
  "reaction",
  "addressed",

  // Business / Career
  "brand deal",
  "partnership",
  "investment",
  "startup",
  "business",
  "company",
  "acquisition",
  "funding",
  "contract",
  "endorsement",
  "net worth",
  "earnings",

  // Shows / Professional
  "show announcement",
  "season",
  "new show",
  "guest appearance",
  "interview",
  "podcast appearance",
  "award",
  "nomination",
  "winner",
  "netflix",
  "amazon prime",
  "hotstar",
  "television",
  "tv show",

  // Sensitive
  "death",
  "hospital",
  "injury",
  "accident",
  "health update",
  "security issue",
  "threat",
  "attack",
  "fraud",
  "scam",
  "hack",
  "leaked",
  "leak",
  "global",
  "record",
  "failed",
  "socially",
  "emotional",
  "spoke",
  "against",
  "interview",
  "cryptic",
  "note",
  "powerfull",
  "unpredictable",
  "serious",
  "circuit",
  "still alive",
  "opened up",
  "internet",
  "sunil pal",
  "laughter chefs",
];

export const FUN_KEYWORDS = [
  "vlog",
  "daily life",
  "day in my life",
  "travel",
  "vacation",
  "trip",
  "airport",
  "family",
  "friends",
  "birthday",
  "celebration",
  "weekend",
  "outing",

  // Comedy
  "funny",
  "comedy",
  "joke",
  "jokes",
  "meme",
  "memes",
  "roast",
  "banter",
  "laugh",
  "hilarious",
  "viral moment",
  "reaction video",

  // Edits / Fan Content
  "edit",
  "fan edit",
  "tribute",
  "fanpage",
  "fan moment",
  "montage",
  "compilation",
  "best moments",
  "throwback",

  // Music
  "song",
  "music",
  "album",
  "track",
  "single",
  "music video",
  "lyrical",
  "dance",
  "performance",
  "dj",
  "remix",

  // Reels / Shorts
  "reel",
  "reels",
  "shorts",
  "instagram reel",
  "youtube shorts",
  "challenge",
  "trend",
  "trending",
  "viral",
  "dance trend",

  // Gaming
  "gaming",
  "gameplay",
  "stream",
  "livestream",
  "stream clip",
  "esports",
  "chess",
  "valorant",
  "bgmi",
  "minecraft",

  // Creator Moments
  "wholesome",
  "cute",
  "heartwarming",
  "emotional",
  "friendship",
  "creator moment",
  "podcast clip",
  "fun clip",
  "behind the scenes",
  "bts",

  // Entertainment
  "collab",
  "collaboration",
  "prank",
  "challenge video",
  "fun challenge",
  "trailer",
  "teaser",
  "episode",
  "show clip",
  "movie release",
  "web series",
  "entertainment",

  // Lifestyle
  "fitness",
  "food",
  "cooking",
  "shopping",
  "fashion",
  "style",
  "makeover",
  "routine",
  "life update",

  // Social Media
  "instagram",
  "youtube video",
  "creator post",
  "viral reel",
  "viral clip",
  "fan interaction",
  "qna",
  "ask me anything",
  // Elvish branding
  "rao sahab",
  "elvish army",
  "system",
  "system hang",
  "elvishians",

  // Lifestyle
  "luxury car",
  "supercar",
  "car collection",
  "new car",
  "bike ride",
  "road trip",
  "farmhouse",
  "village life",
  "haryana",
  "gurgaon",

  // Friends & gang
  "gang",
  "boys",
  "brothers",
  "friendship",
  "club",
  "club scene",
  "party",
  "nightlife",
  "ladai",
  "fight clip",
  "funny fight",

  // Music
  "chand mera dil",
  "romantic",
  "love song",
  "music reel",
  "sad song",
  "heartbreak",
  "shayari",
  "poetry",

  // Spiritual
  "mahadev",
  "shiv",
  "har har mahadev",
  "faith",
  "spiritual",
  "blessings",
  "god",
  "temple",
  "pendant",
  "positive energy",

  // Fan content
  "fan edit",
  "elvish edit",
  "viral edit",
  "army edit",
  "tribute edit",

  // Daily creator content
  "behind the scenes",
  "bts",
  "vlog",
  "travel vlog",
  "daily vlog",
  "creator life",
  "fun conversation",
  "live stream",
  "podcast clip",

  // Brand promotions
  "link in bio",
  "download now",
  "promo",
  "promotion",
  "brand collaboration",
  "partnered with",
  "sponsored",

  // Social content
  "reels",
  "fyp",
  "explore",
  "trending reel",
  "viral reel",
  "challenge",
  "funny moment",
];

export const CREATOR_NAMES = [
  {
    name: "Samay_Raina",
    keywords: [
      "samay raina",
      "india's got latent",
      "indias got latent",
      "samay raina controversy",
      "samay raina news",
      "samay raina FIR",
      "samay raina court case",
      "samay raina legal notice",
      "indias got latent",
      "samay raina apology",
      "samay raina comeback",
    ],
    channelName: "@SamayRainaOfficial",
  },
  {
    name: "Elvish_Yadav",
    keywords: [
      "rao sahab",
      "elvishyadav",
      "elvisharmy",
      "elvish",
      "systemclothing",
      "elvishians",
      "elvishsquad",
      "rao_sahab",
      "elvishyadavvlogs",
      "elvishyadavfans",
      "elvishyadavofficial",
      "elvisharmyofficial",
      "systumm",
      "elvishbhaiii",
      "raosahab",
    ],
    channelName: "@ElvishYadavVlogs",
  },
];
